import type { ReactElement } from "react";
import { NextPageWithLayout } from "../_app";
import DashboardLayout from "@/layouts/DashboardLayout";
import Head from "next/head";
import { IconMail } from "@tabler/icons-react";
import InputRounded from "@/components/ui/InputRounded";

const DashboardCreate: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Dashboard - Create</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mx-auto flex w-11/12 max-w-4xl flex-col items-center gap-10 py-10 lg:py-20">
        <div className="flex flex-col items-center gap-4">
          <p className="text-3xl font-bold lg:text-4xl">Create a new hackathon</p>
          <p className="text-lg">Create an extraordinary hackathon experience with our creation page. Customize challenges, formats, and settings to inspire innovation and collaboration. Unleash your creativity and shape a remarkable event that cultivates talent. Get started today!</p>
        </div>

        <form className="flex w-full">
          <div className="w-6/12">
            <InputRounded leadingIcon={<IconMail className="h-6 w-6" />} placeholderOffset="pl-14" errorMessage="Enter a name for the hackathon" id="nameInput" type="text" placeholder="Name">
              Name
            </InputRounded>
          </div>
          <div className="w-6/12"></div>
        </form>
      </div>
    </>
  );
};

DashboardCreate.getLayout = function getLayout(page: ReactElement) {
  return <DashboardLayout>{page}</DashboardLayout>;
};

export default DashboardCreate;
