import { IconMailFilled } from "@tabler/icons-react";
import Image from "next/image";
import Link from "next/link";
import Head from "next/head";

export default function ForgotPassword() {
  return (
    <>
      <Head>
        <title>Confirm email</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative mx-auto flex min-h-screen w-11/12 flex-col items-center justify-between gap-10 bg-cloud bg-repeat-round py-10">
        <div />
        <section className="mx-auto flex w-full max-w-6xl rounded-lg bg-white shadow-lg">
          <div className="flex w-full flex-col gap-6 px-6 py-8 lg:w-3/5 lg:p-20">
            <div className="flex justify-center">
              <IconMailFilled className="h-20 w-20 text-primary" />
            </div>

            <div className="flex flex-col gap-2 text-center">
              <p className="text-2xl font-bold">Confirm your email</p>
              <p className="text-lg">
                Open your email to activate your account!
              </p>
            </div>
          </div>

          <div className="hidden w-2/5 flex-col items-center justify-center gap-4 rounded-lg bg-gradient-primary p-10 lg:flex">
            <p className="text-center text-2xl font-bold text-white">
              Why do we confirm our email?
            </p>

            <p className="text-center leading-relaxed text-gray-200">
              Confirming your email is crucial for a seamless experience with
              our services. By verifying your email, you activate your account,
              granting you access to all our features and benefits. It also
              ensures effective communication, allowing us to keep you informed
              about important updates, notifications, and exclusive offers.
              Think of it as unlocking a door to a world of possibilities, where
              you can stay connected and up-to-date with everything our
              community has to offer.
            </p>
          </div>
        </section>

        <div className="flex items-center gap-6 lg:gap-20">
          <Link
            className="block h-[48px] w-[150px]"
            href="https://www.brainster.co/"
          >
            <Image
              src="/images/logos/brainster-logo.png"
              width={150}
              height={48}
              alt="Brainster Logo"
              fetchPriority="high"
            />
          </Link>

          <Link
            className="block h-[48px] w-[150px]"
            href="https://scidevcenter.org/"
          >
            <Image
              src="/images/logos/scidev-logo.png"
              alt="SCIDev Logo"
              width={150}
              height={48}
              priority
            />
          </Link>
        </div>
      </main>
    </>
  );
}
